package valfield

const (
	Active     = "active"
	UName      = "uname"
	Email      = "email"
	Name       = "name"
	Password   = "pwd"
	Regtime    = "regtime"
	Phone      = "phone"
	Country    = "country"
	City       = "city"
	Addr       = "addr"
	SysRole    = "sysRole"
	MemLevel   = "memLevel"
	MemExpire  = "memExpire"
	NationalID = "nationalid"
	Gender     = "gender"
	DOB        = "dob"
	Position   = "position"
	Title      = "title"
	Employer   = "employer"
	Bio        = "bio"
	Tags       = "tags"
	AvatarType = "avatartype"
	Avatar     = "avatar"
)
