package registered

import (
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"testing"
	"time"

	. "github.com/digisan/go-generics/v2"
	fd "github.com/digisan/gotk/file-dir"
	"github.com/digisan/gotk/strs"
	lk "github.com/digisan/logkit"
	. "github.com/digisan/user-mgr/util"
)

func TestIterTags(t *testing.T) {
	fmt.Println(ListField(User{}, User{}.Core, User{}.Profile, User{}.Admin))
	fmt.Println(ListValidator(User{}, User{}.Core, User{}.Profile, User{}.Admin))
}

func TestFieldValue(t *testing.T) {
	user := &User{
		Core{
			UName:    "unique-user-name",
			Email:    "hello@abc.com",
			Password: "123456789a",
			key:      [16]byte{},
		},
		Profile{
			Name:           "test-name",
			Phone:          "",
			Country:        "",
			City:           "",
			Addr:           "",
			PersonalIDType: "",
			PersonalID:     "9876543210",
			Gender:         "",
			DOB:            "",
			Position:       "professor",
			Title:          "",
			Employer:       "",
			Bio:            "",
			AvatarType:     "image/png",
			Avatar:         []byte("******"),
		},
		Admin{
			RegTime:   time.Time{},
			Active:    true,
			Certified: false,
			Official:  false,
			SysRole:   "",
			MemLevel:  0,
			MemExpire: time.Time{},
			Notes:     "",
			Status:    "",
		},
	}

	fmt.Println(FieldValue(user, "UName"))
	// fmt.Println(user.FieldValue("key")) // panic
	fmt.Println(FieldValue(user, "Avatar"))

	if err := SetField(user, "Name", "MODIFIED-NAME"); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("%+v\n", *user)

	user.AddNotes("abc", "def")
	fmt.Println("notes:", user.GetNotes())

	user.RmNotes("abc")
	fmt.Println("notes:", user.GetNotes())
}

func TestUser(t *testing.T) {

	user := &User{
		Core{
			UName:    "unique-user-name",
			Email:    "hello@abc.com",
			Password: "123456789a",
			key:      [16]byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
		},
		Profile{
			Name:           "test-name",
			Phone:          "",
			Country:        "",
			City:           "",
			Addr:           "",
			PersonalIDType: "",
			PersonalID:     "987654321011",
			Gender:         "",
			DOB:            "",
			Position:       "professor",
			Title:          "",
			Employer:       "",
			Bio:            "",
			AvatarType:     "image/png",
			Avatar:         []byte("******"),
		},
		Admin{
			RegTime:   time.Now().Truncate(time.Second), // must Truncate, otherwise Unmarshal error
			Active:    true,
			Certified: false,
			Official:  false,
			SysRole:   "",
			MemLevel:  3,
			MemExpire: time.Time{},
			Notes:     "",
			Status:    "",
		},
	}

	// ava := make([]byte, 0, 20000000)
	// for i := 0; i < 20000000; i++ {
	// 	ava = append(ava, byte(i%100))
	// }
	// user.Avatar = ava

	info, key := user.Marshal(nil)
	fmt.Println("user.key", user.key)

	fmt.Println()

	fmt.Println(user)
	fmt.Println()

	// key[1] = 2

	user1 := &User{}
	user1.Unmarshal(info, key)
	fmt.Println(user1)

	fmt.Println("user == user1 :", user == user1)
	fmt.Println("reflect.DeepEqual(*user.COre, *user1.Core) :", reflect.DeepEqual(user.Core, user1.Core))
	fmt.Println("reflect.DeepEqual(*user.Profile, *user1.Profile) :", reflect.DeepEqual(user.Profile, user1.Profile))
	fmt.Println("reflect.DeepEqual(*user.Admin, *user1.Admin) :", reflect.DeepEqual(user.Admin, user1.Admin))
	lk.FailOnErrWhen(!reflect.DeepEqual(*user, *user1), "%v", fmt.Errorf("Marshal-Unmarshal ERROR"))
}

// *** Auto Generate Validate Field Tag Const, Output is in ../validate/auto-tags.go *** //
func TestMakeUserFieldTag(t *testing.T) {
	const pkg = "user"
	const file = "../validate-tags.go"
	fd.MustAppendFile(file, []byte("// This file is AUTO Generated by user_test.go/TestMakeUserFieldTag\n"), true)
	fd.MustAppendFile(file, []byte("package "+pkg+"\n"), true)
	fd.MustAppendFile(file, []byte("const ("), true)
	defer fd.MustAppendFile(file, []byte("\n)"), false)

	const TAG = "validate"
	// r := regexp.MustCompile(`((required),?)|((email),?)`) // exclude default validator tags
	r := regexp.MustCompile(`(required),?`)

	for _, obj := range []any{Core{}, Profile{}, Admin{}} {
		typ := reflect.TypeOf(obj)
		for i := 0; i < typ.NumField(); i++ {
			field := typ.Field(i)
			tags := field.Tag.Get(TAG)
			// fmt.Printf("%d. %v (%v), tag: '%v'\n", i+1, field.Name, field.Type.Name(), tag)
			tags = r.ReplaceAllString(tags, "")
			if len(tags) > 0 {
				for _, tag := range strings.Split(tags, ",") {
					suffix := ""
					if strings.Contains(tag, "-") {
						suffix = strings.ToTitle(strs.SplitPartFromLastTo[string](tag, "-", 1))
					}
					line := fmt.Sprintf("\t%s = \"%s\"", field.Name+suffix, tag)
					fd.MustAppendFile(file, []byte(line), true)
				}
			}
		}
	}
}
