// This file is AUTO Generated by user_test.go/TestMakeUserFieldTag

package valfield

const (
	UName = "uname"
	Email = "email"
	EmailDB = "email-db"
	Password = "pwd"
	Name = "name"
	Phone = "phone"
	PhoneDB = "phone-db"
	Country = "country"
	City = "city"
	Addr = "addr"
	PersonalIDType = "personalidtype"
	PersonalID = "personalid"
	Gender = "gender"
	DOB = "dob"
	Position = "position"
	Title = "title"
	Employer = "employer"
	Bio = "bio"
	AvatarType = "avatartype"
	Avatar = "avatar"
	RegTime = "regtime"
	Active = "active"
	Certified = "certified"
	Official = "official"
	SysRole = "sysRole"
	MemLevel = "memLevel"
	MemExpire = "memExpire"
	Tags = "tags"
)